version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "forum"
    ports:
      - "15432:5432"
    volumes:
      - ./database/dbdocker:/var/lib/postgresql/data
    networks:
      - prod

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "sistemas.glauber@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "docker"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - prod

networks:
  prod:
    driver: bridge
